// SPDX-License-Identifier: MIT OR Apache-2.0

//! Cross-validation tests for `BitsAndBytes` dequantization against `PyTorch` reference.
//!
//! These tests load pre-computed fixtures generated by
//! `tests/fixtures/bnb_reference/generate_bnb.py` and compare anamnesis
//! `BnB` dequantization output against the `bitsandbytes` formula.

#![cfg(feature = "bnb")]
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::as_conversions,
    clippy::cast_possible_truncation,
    clippy::similar_names,
    clippy::wildcard_enum_match_arm
)]

mod common;

use std::time::Instant;

use anamnesis::remember::bnb::{
    dequantize_bnb4_double_quant, dequantize_bnb4_double_quant_to_bf16,
};
use anamnesis::{
    F32Out, dequantize_bnb_int8, dequantize_bnb_int8_to_bf16, dequantize_bnb4,
    dequantize_bnb4_to_bf16,
};

use common::bf16::{SignedZero, compare_bf16_with};
use common::bnb::{parse_bnb4_fixture, parse_int8_fixture};

// ---------------------------------------------------------------------------
// F32 comparison
// ---------------------------------------------------------------------------

/// Compares `F32` output against `bitsandbytes` **bit for bit**.
///
/// No tolerance, by design. The `BF16` comparison carries a `ULP` budget
/// because narrowing to 8 significand bits is a lossy step both sides perform.
/// `F32` has no such excuse: both compute in `f32`, so identical operations in
/// identical order must give identical bits.
///
/// **One documented exemption**, inherited from `compare_bf16`: `±0` are
/// arithmetically identical, and anamnesis' `BnB4` decode deliberately emits
/// `-0.0` where a codebook entry with the nibble high bit set collapsed to
/// `+0.0` — the sign-of-zero preservation rule that lets encode round-trip the
/// original nibble byte-exactly, while `bitsandbytes`' decode emits `+0.0`
/// there. The count is reported separately so the exemption stays visibly
/// narrow rather than quietly absorbing real mismatches.
fn compare_f32_exact(name: &str, actual: &[u8], expected: &[u8]) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{name}: F32 output length mismatch"
    );

    let mut mismatches = 0usize;
    let mut signed_zeros = 0usize;
    let mut first: Option<(usize, f32, f32)> = None;
    for (i, (a_word, e_word)) in actual
        .as_chunks::<4>()
        .0
        .iter()
        .zip(expected.as_chunks::<4>().0)
        .enumerate()
    {
        let a = f32::from_le_bytes([a_word[0], a_word[1], a_word[2], a_word[3]]);
        let e = f32::from_le_bytes([e_word[0], e_word[1], e_word[2], e_word[3]]);
        // Bit equality, not `==`: `NaN` payloads and signed zero must count.
        if a.to_bits() == e.to_bits() {
            continue;
        }
        // BITWISE: low 31 bits zero ⇒ value is +0 or -0 (sign-only diff), the
        // f32 counterpart of `compare_bf16`'s low-15-bits test.
        if a.to_bits().trailing_zeros() >= 31 && e.to_bits().trailing_zeros() >= 31 {
            signed_zeros += 1;
            continue;
        }
        mismatches += 1;
        if first.is_none() {
            first = Some((i, a, e));
        }
    }

    eprintln!("  F32: {mismatches} mismatches, {signed_zeros} sign-of-zero-only differences");
    if let Some((i, a, e)) = first {
        eprintln!(
            "  F32 element {i}: actual={a:e} (0x{:08X}), expected={e:e} (0x{:08X})",
            a.to_bits(),
            e.to_bits()
        );
    }
    assert_eq!(
        mismatches,
        0,
        "{name}: {mismatches}/{} F32 elements differ from bitsandbytes. This is NOT \
         a tolerance question — both sides compute in f32. Treat it as a real \
         finding before touching the test.",
        actual.len() / 4
    );
}

// ---------------------------------------------------------------------------
// BF16 comparison
// ---------------------------------------------------------------------------

/// The shared `BF16` comparison with the `BnB` suite's one variant: signed
/// zero counts as a match.
///
/// IEEE 754 signed-zero equivalence: +0 and -0 are arithmetically
/// identical. anamnesis' `BnB4` decode emits -0 for nibble high-bit
/// entries whose codebook value collapsed to +0 (the sign-of-zero
/// preservation rule that lets encode round-trip the original
/// nibble byte-exactly); `bitsandbytes`' Python decode emits +0 at
/// those positions. The arithmetic value is the same. Every other suite
/// compares with `SignedZero::Distinct`.
fn compare_bf16(actual: &[u8], expected: &[u8], max_ulp_diff: u16) -> (usize, u16) {
    compare_bf16_with(actual, expected, max_ulp_diff, SignedZero::Equivalent)
}

// ---------------------------------------------------------------------------
// Test runners
// ---------------------------------------------------------------------------

fn run_bnb4_cross_validation(name: &str, data: &[u8], max_ulp: u16) {
    let fixture = parse_bnb4_fixture(data);

    let format_label = match fixture.format_id {
        0 => "NF4/FP4",
        2 => "NF4/FP4 double-quant",
        other => panic!("unknown format_id: {other}"),
    };

    eprintln!(
        "{name}: {format_label}, block_size={}, {} elements",
        fixture.block_size, fixture.total_elements,
    );

    // Infer nested_block_size: absmax_count / nested_absmax_count
    let absmax_count = fixture.absmax_data.len();
    let nested_absmax_count = fixture.nested_absmax_data.len() / 4;
    let nested_block_size = if nested_absmax_count > 0 {
        absmax_count.div_ceil(nested_absmax_count)
    } else {
        256
    };

    let start = Instant::now();
    let actual = if fixture.format_id == 2 {
        dequantize_bnb4_double_quant_to_bf16(
            &fixture.weight_data,
            &fixture.absmax_data,
            &fixture.quant_map_data,
            &fixture.nested_absmax_data,
            &fixture.nested_quant_map_data,
            fixture.nested_offset,
            fixture.total_elements,
            fixture.block_size,
            nested_block_size,
        )
        .expect("BnB4 double-quant dequantization failed")
    } else {
        dequantize_bnb4_to_bf16(
            &fixture.weight_data,
            &fixture.absmax_data,
            &fixture.quant_map_data,
            fixture.total_elements,
            fixture.block_size,
        )
        .expect("BnB4 dequantization failed")
    };
    let elapsed = start.elapsed();

    let (mismatches, max_diff) = compare_bf16(&actual, &fixture.expected_bf16, max_ulp);
    eprintln!(
        "  {mismatches} mismatches, max ULP diff = {max_diff}, anamnesis = {:.1} µs",
        elapsed.as_secs_f64() * 1e6,
    );
    assert_eq!(
        mismatches, 0,
        "{name}: {mismatches} BF16 mismatches (max ULP diff = {max_diff})"
    );

    let actual_f32 = if fixture.format_id == 2 {
        dequantize_bnb4_double_quant::<F32Out>(
            &fixture.weight_data,
            &fixture.absmax_data,
            &fixture.quant_map_data,
            &fixture.nested_absmax_data,
            &fixture.nested_quant_map_data,
            fixture.nested_offset,
            fixture.total_elements,
            fixture.block_size,
            nested_block_size,
        )
        .expect("BnB4 double-quant F32 dequantization failed")
    } else {
        dequantize_bnb4::<F32Out>(
            &fixture.weight_data,
            &fixture.absmax_data,
            &fixture.quant_map_data,
            fixture.total_elements,
            fixture.block_size,
        )
        .expect("BnB4 F32 dequantization failed")
    };
    compare_f32_exact(name, &actual_f32, &fixture.expected_f32);
}

fn run_int8_cross_validation(name: &str, data: &[u8], max_ulp: u16) {
    let fixture = parse_int8_fixture(data);

    eprintln!(
        "{name}: INT8, {}×{} = {} elements",
        fixture.out_features,
        fixture.in_features,
        fixture.out_features * fixture.in_features,
    );

    let start = Instant::now();
    let actual = dequantize_bnb_int8_to_bf16(
        &fixture.weight_data,
        &fixture.scb_data,
        fixture.out_features,
        fixture.in_features,
    )
    .expect("BnB INT8 dequantization failed");
    let elapsed = start.elapsed();

    let (mismatches, max_diff) = compare_bf16(&actual, &fixture.expected_bf16, max_ulp);
    eprintln!(
        "  {mismatches} mismatches, max ULP diff = {max_diff}, anamnesis = {:.1} µs",
        elapsed.as_secs_f64() * 1e6,
    );
    assert_eq!(
        mismatches, 0,
        "{name}: {mismatches} BF16 mismatches (max ULP diff = {max_diff})"
    );

    let actual_f32 = dequantize_bnb_int8::<F32Out>(
        &fixture.weight_data,
        &fixture.scb_data,
        fixture.out_features,
        fixture.in_features,
    )
    .expect("BnB INT8 F32 dequantization failed");
    compare_f32_exact(name, &actual_f32, &fixture.expected_f32);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn cross_validate_llama_1b_nf4() {
    let data = include_bytes!("fixtures/bnb_reference/llama_1b_nf4.bin");
    run_bnb4_cross_validation("Llama-3.2-1B NF4", data, 0);
}

#[test]
fn cross_validate_llama_1b_nf4_double_quant() {
    let data = include_bytes!("fixtures/bnb_reference/llama_1b_nf4_double_quant.bin");
    run_bnb4_cross_validation("Llama-3.2-1B NF4 double-quant", data, 0);
}

#[test]
fn cross_validate_llama_1b_fp4() {
    let data = include_bytes!("fixtures/bnb_reference/llama_1b_fp4.bin");
    run_bnb4_cross_validation("Llama-3.2-1B FP4", data, 0);
}

#[test]
fn cross_validate_llama_1b_int8() {
    let data = include_bytes!("fixtures/bnb_reference/llama_1b_int8.bin");
    run_int8_cross_validation("Llama-3.2-1B INT8", data, 0);
}

#[test]
fn cross_validate_qwen3_mcqa_fp4() {
    // Step 1b — cross-architecture plain-FP4 decode validation.
    // Same on-disk codebook structure as `llama_1b_fp4` (`+0.0` at both
    // index 0 and index 8); decode exercises the sign-of-zero
    // preservation rule on a different architecture (Qwen3) and HF org
    // (`ema1234`). `compare_bf16` treats `±0` as IEEE-equivalent, so
    // the sign-of-zero divergence from bitsandbytes' Python decode does
    // not break bit-exactness.
    let data = include_bytes!("fixtures/bnb_reference/qwen3_mcqa_fp4.bin");
    run_bnb4_cross_validation("Qwen3 MCQA FP4", data, 0);
}

#[test]
fn cross_validate_qwen2_5_1_5b_nf4_dq() {
    // Step 1c — cross-architecture NF4 double-quant decode validation.
    // Qwen2.5 architecture from the unsloth org. Surfaced by
    // `hf-fm inspect` during candidate selection: every non-Llama
    // BnB-NF4 model checked uses double-quant (the bitsandbytes
    // default). This fixture extends decode coverage to a second
    // architecture under the DQ layout.
    let data = include_bytes!("fixtures/bnb_reference/qwen2_5_1_5b_nf4_dq.bin");
    run_bnb4_cross_validation("Qwen2.5-1.5B NF4 double-quant", data, 0);
}

#[test]
fn cross_validate_phi3_5_mini_nf4_dq() {
    // Step 1c — cross-architecture NF4 double-quant decode validation.
    // Phi-3.5 architecture from the unsloth org. Third architecture
    // family (after Llama and Qwen) validating the NF4 DQ decode path.
    let data = include_bytes!("fixtures/bnb_reference/phi3_5_mini_nf4_dq.bin");
    run_bnb4_cross_validation("Phi-3.5-mini NF4 double-quant", data, 0);
}
