// SPDX-License-Identifier: MIT OR Apache-2.0

//! Cross-validation of `.pth` parsing against `PyTorch` reference data.
//!
//! Each test loads an `AlgZoo` `.pth` file with `parse_pth()`, then compares
//! tensor names, shapes, dtypes, and **raw bytes** against a JSON manifest
//! generated by `PyTorch` (`generate_pth_reference.py`). A mismatch at any
//! byte means the pickle VM or tensor extraction diverged from `PyTorch`.
//!
//! # Fixtures
//!
//! | File | Source | Architecture | Format |
//! |------|--------|-------------|--------|
//! | `algzoo_rnn_small.pth` | `AlgZoo` `2nd_argmax_2_2` | RNN (3 tensors, 10 params) | Newer `PyTorch` (`archive/` prefix) |
//! | `algzoo_transformer_small.pth` | `AlgZoo` `longest_cycle_2_3` | Transformer (7 tensors, 50 params) | Newer `PyTorch` (`archive/` prefix) |
//! | `algzoo_rnn_blog.pth` | `AlgZoo` blog example | RNN (3 tensors, 432 params) | Older `PyTorch` (model-name prefix) |

#![cfg(feature = "pth")]
#![allow(
    clippy::panic,
    clippy::indexing_slicing,
    clippy::unwrap_used,
    clippy::as_conversions,
    clippy::wildcard_enum_match_arm
)]

use std::path::PathBuf;

use anamnesis::{PthInspectInfo, inspect_pth_from_reader, parse_pth};

/// Minimal JSON reference structure (deserialized with serde).
#[derive(serde::Deserialize)]
struct Reference {
    num_tensors: usize,
    tensors: Vec<TensorRef>,
}

#[derive(serde::Deserialize)]
struct TensorRef {
    name: String,
    shape: Vec<usize>,
    dtype: String,
    data_hex: String,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("pth_reference")
}

fn load_reference(json_name: &str) -> Reference {
    let path = fixture_dir().join(json_name);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

/// Core cross-validation: parse the .pth file with our Rust parser, then
/// compare every tensor against the Python-generated reference.
fn cross_validate(pth_name: &str, json_name: &str) {
    let pth_path = fixture_dir().join(pth_name);
    let parsed =
        parse_pth(&pth_path).unwrap_or_else(|e| panic!("parse_pth({pth_name}) failed: {e}"));
    let tensors = parsed.tensors().unwrap();

    let reference = load_reference(json_name);

    assert_eq!(
        tensors.len(),
        reference.num_tensors,
        "tensor count mismatch for {pth_name}: rust={}, python={}",
        tensors.len(),
        reference.num_tensors
    );

    for (rust_tensor, py_ref) in tensors.iter().zip(reference.tensors.iter()) {
        // Name
        assert_eq!(
            rust_tensor.name, py_ref.name,
            "tensor name mismatch in {pth_name}"
        );

        // Shape
        assert_eq!(
            rust_tensor.shape, py_ref.shape,
            "shape mismatch for tensor `{}` in {pth_name}: rust={:?}, python={:?}",
            rust_tensor.name, rust_tensor.shape, py_ref.shape
        );

        // Dtype
        assert_eq!(
            rust_tensor.dtype.to_string(),
            py_ref.dtype,
            "dtype mismatch for tensor `{}` in {pth_name}: rust={}, python={}",
            rust_tensor.name,
            rust_tensor.dtype,
            py_ref.dtype
        );

        // Raw bytes — the definitive test: byte-exact match
        let expected_bytes = hex_to_bytes(&py_ref.data_hex);
        assert_eq!(
            rust_tensor.data.len(),
            expected_bytes.len(),
            "data length mismatch for tensor `{}` in {pth_name}: rust={}, python={}",
            rust_tensor.name,
            rust_tensor.data.len(),
            expected_bytes.len()
        );
        assert_eq!(
            rust_tensor.data.as_ref(),
            expected_bytes.as_slice(),
            "DATA MISMATCH for tensor `{}` in {pth_name}: \
             first differing byte at position {}",
            rust_tensor.name,
            rust_tensor
                .data
                .iter()
                .zip(expected_bytes.iter())
                .position(|(a, b)| a != b)
                .unwrap_or(0)
        );
    }
}

// -- `AlgZoo` RNN (newer PyTorch format, archive/ prefix) ----------------------

#[test]
fn cross_validate_algzoo_rnn_small() {
    cross_validate("algzoo_rnn_small.pth", "algzoo_rnn_small_reference.json");
}

// -- `AlgZoo` Transformer (newer PyTorch format, archive/ prefix) --------------

#[test]
fn cross_validate_algzoo_transformer_small() {
    cross_validate(
        "algzoo_transformer_small.pth",
        "algzoo_transformer_small_reference.json",
    );
}

// -- `AlgZoo` RNN blog post (older PyTorch format, model-name prefix) ----------

#[test]
fn cross_validate_algzoo_rnn_blog() {
    cross_validate("algzoo_rnn_blog.pth", "algzoo_rnn_blog_reference.json");
}

// -- Roundtrip: .pth → .safetensors → read back → compare ------------------

/// Parse a `.pth`, convert to `.safetensors`, read the `.safetensors` back,
/// and verify all tensor data matches the `PyTorch` reference byte-for-byte.
fn roundtrip_to_safetensors(pth_name: &str, json_name: &str) {
    let pth_path = fixture_dir().join(pth_name);
    let parsed = parse_pth(&pth_path).unwrap();
    let tensors = parsed.tensors().unwrap();

    // Write to a temporary .safetensors file. Use a TempDir + fresh path
    // rather than NamedTempFile.path(): safetensors' `serialize_to_file` opens
    // the path itself, which on Windows collides with the handle a
    // NamedTempFile keeps open on the same file.
    let dir = tempfile::tempdir().unwrap();
    let st_path = dir.path().join("out.safetensors");
    anamnesis::pth_to_safetensors(&tensors, &st_path).unwrap();

    // Read the .safetensors back.
    let st_data = std::fs::read(&st_path).unwrap();
    let st = safetensors::SafeTensors::deserialize(&st_data).unwrap();

    // Compare against Python reference.
    let reference = load_reference(json_name);
    assert_eq!(st.len(), reference.num_tensors);

    for py_ref in &reference.tensors {
        let st_tensor = st
            .tensor(&py_ref.name)
            .unwrap_or_else(|e| panic!("tensor `{}` not in safetensors: {e}", py_ref.name));

        assert_eq!(
            st_tensor.shape().to_vec(),
            py_ref.shape,
            "shape mismatch after roundtrip for tensor `{}`",
            py_ref.name
        );

        let expected_bytes = hex_to_bytes(&py_ref.data_hex);
        assert_eq!(
            st_tensor.data(),
            expected_bytes.as_slice(),
            "DATA MISMATCH after roundtrip for tensor `{}`",
            py_ref.name
        );
    }
}

#[test]
fn roundtrip_algzoo_rnn_small() {
    roundtrip_to_safetensors("algzoo_rnn_small.pth", "algzoo_rnn_small_reference.json");
}

#[test]
fn roundtrip_algzoo_transformer_small() {
    roundtrip_to_safetensors(
        "algzoo_transformer_small.pth",
        "algzoo_transformer_small_reference.json",
    );
}

#[test]
fn roundtrip_algzoo_rnn_blog() {
    roundtrip_to_safetensors("algzoo_rnn_blog.pth", "algzoo_rnn_blog_reference.json");
}

// -- Roundtrip via bytes: .pth → in-memory safetensors → deserialize → compare --

/// Parse a `.pth`, convert to in-memory safetensors bytes via
/// [`ParsedPth::to_safetensors_bytes`], deserialize, and verify all tensor
/// data matches the `PyTorch` reference byte-for-byte.
fn roundtrip_via_bytes(pth_name: &str, json_name: &str) {
    let pth_path = fixture_dir().join(pth_name);
    let parsed = parse_pth(&pth_path).unwrap();

    // Convert to in-memory safetensors bytes.
    let st_data = parsed.to_safetensors_bytes().unwrap();

    // Deserialize the safetensors bytes.
    let st = safetensors::SafeTensors::deserialize(&st_data).unwrap();

    // Compare against Python reference.
    let reference = load_reference(json_name);
    assert_eq!(st.len(), reference.num_tensors);

    for py_ref in &reference.tensors {
        let st_tensor = st
            .tensor(&py_ref.name)
            .unwrap_or_else(|e| panic!("tensor `{}` not in safetensors: {e}", py_ref.name));

        assert_eq!(
            st_tensor.shape().to_vec(),
            py_ref.shape,
            "shape mismatch after bytes roundtrip for tensor `{}`",
            py_ref.name
        );

        let expected_bytes = hex_to_bytes(&py_ref.data_hex);
        assert_eq!(
            st_tensor.data(),
            expected_bytes.as_slice(),
            "DATA MISMATCH after bytes roundtrip for tensor `{}`",
            py_ref.name
        );
    }
}

#[test]
fn roundtrip_bytes_algzoo_rnn_small() {
    roundtrip_via_bytes("algzoo_rnn_small.pth", "algzoo_rnn_small_reference.json");
}

#[test]
fn roundtrip_bytes_algzoo_transformer_small() {
    roundtrip_via_bytes(
        "algzoo_transformer_small.pth",
        "algzoo_transformer_small_reference.json",
    );
}

#[test]
fn roundtrip_bytes_algzoo_rnn_blog() {
    roundtrip_via_bytes("algzoo_rnn_blog.pth", "algzoo_rnn_blog_reference.json");
}

// ---------------------------------------------------------------------------
// Reader-generic API — substrate equivalence on the AlgZoo fixtures (Phase 4.10)
// ---------------------------------------------------------------------------
//
// Asserts that `inspect_pth_from_reader` returns the same `PthInspectInfo` as
// `parse_pth(path).inspect()` on every AlgZoo fixture, across both an
// in-memory `Cursor<&[u8]>` substrate and a real `std::fs::File`. This is the
// contract that downstream `HTTP`-range adapters rely on: the substrate
// (file vs. cursor vs. range-backed transport) cannot change the metadata.

/// Asserts every field of two `PthInspectInfo` values is equal.
fn assert_pth_inspect_eq(label: &str, a: &PthInspectInfo, b: &PthInspectInfo) {
    assert_eq!(a.tensor_count, b.tensor_count, "{label}: tensor_count");
    assert_eq!(a.total_bytes, b.total_bytes, "{label}: total_bytes");
    assert_eq!(a.dtypes, b.dtypes, "{label}: dtypes");
    assert_eq!(a.big_endian, b.big_endian, "{label}: big_endian");
}

/// Inspects every `AlgZoo` fixture through three different substrates —
/// the mmap-backed `parse_pth`, a `Cursor<&[u8]>` over the file's
/// in-memory bytes, and a real `std::fs::File` — and asserts the resulting
/// `PthInspectInfo` is field-for-field identical across all three.
#[test]
fn substrate_equivalence_algzoo_fixtures() {
    let fixtures = [
        "algzoo_rnn_small.pth",
        "algzoo_transformer_small.pth",
        "algzoo_rnn_blog.pth",
    ];

    for name in fixtures {
        let path = fixture_dir().join(name);

        // Substrate 1: path-based (mmap-backed).
        let path_info = parse_pth(&path)
            .unwrap_or_else(|e| panic!("parse_pth({name}) failed: {e}"))
            .inspect();

        // Substrate 2: in-memory `Cursor<&[u8]>`.
        let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read({name}) failed: {e}"));
        let cursor_info = inspect_pth_from_reader(std::io::Cursor::new(&bytes))
            .unwrap_or_else(|e| panic!("inspect_pth_from_reader(Cursor) on {name} failed: {e}"));

        // Substrate 3: real `std::fs::File` — exactly what an `HTTP`-range
        // adapter or other custom transport would present.
        let file =
            std::fs::File::open(&path).unwrap_or_else(|e| panic!("open({name}) failed: {e}"));
        let file_info = inspect_pth_from_reader(file)
            .unwrap_or_else(|e| panic!("inspect_pth_from_reader(File) on {name} failed: {e}"));

        assert_pth_inspect_eq(&format!("{name} path vs cursor"), &path_info, &cursor_info);
        assert_pth_inspect_eq(&format!("{name} path vs file"), &path_info, &file_info);
        assert_pth_inspect_eq(&format!("{name} cursor vs file"), &cursor_info, &file_info);
    }
}
